---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: bootstrap
  source:
    repoURL: 'https://github.com/naivary/k8s-argocd.git'
    targetRevision: HEAD
    path: apps/bootstrap/metallb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
